SELECT ST.SOLUCIONTECNOLOGICA                                                           AS CODIGO_SOLUCION,
       COUNT(DISTINCT S.ID_SUFRAGIO)                                                    AS TOTAL,
       COUNT(DISTINCT S.ID_SUFRAGIO) * CP.CANTIDAD_PAQUETES                             AS TOTAL_PAQUETE,
       COUNT(CC.ID_SUFRAGIO)                                                            AS PAQUETES_RECIBIDOS,
       ((COUNT(DISTINCT S.ID_SUFRAGIO) * CP.CANTIDAD_PAQUETES) - COUNT(CC.ID_SUFRAGIO)) AS PAQUETES_FALTANTES,
       LTRIM(TO_CHAR(ROUND(((COUNT(CC.ID_SUFRAGIO) / (COUNT(DISTINCT S.ID_SUFRAGIO) * CP.CANTIDAD_PAQUETES)) * 100), 2),
                     '99G990D99MI'))                                                    AS PORCENTAJE_RECIBIDOS,
       LTRIM(TO_CHAR(NVL(ROUND((100 - ROUND(
               ((COUNT(CC.ID_SUFRAGIO) / (COUNT(DISTINCT S.ID_SUFRAGIO) * CP.CANTIDAD_PAQUETES)) * 100), 2)), 2), 0),
                     '99G990D99MI'))                                                    AS PORCENTAJE_FALTANTES
FROM MESA_SUFRAGIO S
         INNER JOIN ODPE O ON S.ID_ODPE = O.ID_ODPE
         INNER JOIN SOLUCIONTECNOLOGICA ST ON ST.ID_SOLUCIONTECNOLOGICA = S.ID_SOLUCION
         INNER JOIN CONSULTA_PROCESO CP ON CP.ID_CONSULTA = S.ID_CONSULTA
         INNER JOIN CONSULTA C ON C.ID_CONSULTA = CP.ID_CONSULTA AND CP.ID_PROCESO = 181
         LEFT JOIN CONTROL_CALIDAD CC
                   ON CC.ID_SUFRAGIO = S.ID_SUFRAGIO AND CC.ID_PROCESO = 181 AND CC.ID_MATERIAL = 1 AND
                      CC.ID_ETAPA = 1 AND CC.VALIDACION = 1
WHERE S.ID_ODPE = 281
  AND S.ID_PROCESO = 181
  AND S.ID_FASE = 1
GROUP BY ST.SOLUCIONTECNOLOGICA, CP.CANTIDAD_PAQUETES

UNION ALL

SELECT 'TOTAL',
       COUNT(DISTINCT S.ID_SUFRAGIO)                                                    AS TOTAL,
       COUNT(DISTINCT S.ID_SUFRAGIO) * CP.CANTIDAD_PAQUETES                             AS TOTAL_PAQUETE,
       COUNT(CC.ID_SUFRAGIO)                                                            AS PAQUETES_RECIBIDOS,
       ((COUNT(DISTINCT S.ID_SUFRAGIO) * CP.CANTIDAD_PAQUETES) - COUNT(CC.ID_SUFRAGIO)) AS PAQUETES_FALTANTES,
       LTRIM(TO_CHAR(ROUND(((COUNT(CC.ID_SUFRAGIO) / (COUNT(DISTINCT S.ID_SUFRAGIO) * CP.CANTIDAD_PAQUETES)) * 100), 2),
                     '99G990D99MI'))                                                    AS PORCENTAJE_RECIBIDOS,
       LTRIM(TO_CHAR(ROUND((100 - ROUND(
               ((COUNT(CC.ID_SUFRAGIO) / (COUNT(DISTINCT S.ID_SUFRAGIO) * CP.CANTIDAD_PAQUETES)) * 100), 2)), 2),
                     '99G990D99MI'))                                                    AS PORCENTAJE_FALTANTES
FROM MESA_SUFRAGIO S
         INNER JOIN ODPE O ON S.ID_ODPE = O.ID_ODPE
         INNER JOIN SOLUCIONTECNOLOGICA ST ON ST.ID_SOLUCIONTECNOLOGICA = S.ID_SOLUCION
         INNER JOIN CONSULTA_PROCESO CP ON CP.ID_CONSULTA = S.ID_CONSULTA
         INNER JOIN CONSULTA C ON C.ID_CONSULTA = CP.ID_CONSULTA AND CP.ID_PROCESO = 181
         LEFT JOIN CONTROL_CALIDAD CC
                   ON CC.ID_SUFRAGIO = S.ID_SUFRAGIO AND CC.ID_PROCESO = 181 AND CC.ID_MATERIAL = 1 AND
                      CC.ID_ETAPA = 1 AND CC.VALIDACION = 1
WHERE S.ID_ODPE = 281
  AND S.ID_PROCESO = 181
  AND S.ID_FASE = 1
GROUP BY CP.CANTIDAD_PAQUETES;